In [2]:
import numpy as np

# Базовые штуки обращения и создания numpy массива

In [4]:
lst = [1, 2, 3]
values = np.array(lst)
lst, values

([1, 2, 3], array([1, 2, 3]))

In [6]:
type(values), type(lst)

(numpy.ndarray, list)

In [7]:
values.dtype

dtype('int64')

In [18]:
values = np.array([1, 2, "3", True])
values

array(['1', '2', '3', 'True'], dtype='<U21')

In [9]:
values[0]

'1'

In [10]:
values[:2]

array(['1', '2'], dtype='<U21')

In [11]:
values[2:4]

array(['3', 'True'], dtype='<U21')

In [12]:
values[1:-1]

array(['2', '3'], dtype='<U21')

In [13]:
values[2] = "123"

values

array(['1', '2', '123', 'True'], dtype='<U21')

In [14]:
values[0] = 321
values

array(['321', '2', '123', 'True'], dtype='<U21')

In [19]:
values = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
values

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
values[2]

3

In [22]:
values[[2,2,2, 1]]

array([3, 3, 3, 2])

In [23]:
values[[True, False, False, True, False, False, False, False,True]]

array([1, 4, 9])

In [24]:
values = np.array([1,2,3,4,5,6,7,8,9])

d2_values = values.reshape(3, 3)

values.shape, d2_values.shape

((9,), (3, 3))

In [25]:
values

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
d2_values

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
d2_values_list = [[1,2,3],[4,5,6], [7,8,9]]
d2_values_list

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [29]:
d2_values[0]

array([1, 2, 3])

In [30]:
d2_values[0][1]

2

In [31]:
d2_values_list[0][1]

2

In [32]:
d2_values[0, 1]

2

In [34]:
# d2_values_list[0, 1]

In [36]:
d2_values[:, 0]

array([1, 4, 7])

In [37]:
d2_values[1]

array([4, 5, 6])

# Типы

In [38]:
values = np.array([1, 2, 3, 4])
values

array([1, 2, 3, 4])

In [39]:
values.dtype

dtype('int64')

In [40]:
values = np.array([1, 2, 3, 4], dtype='float32')
values

array([1., 2., 3., 4.], dtype=float32)

In [44]:
values = np.array([1, 2, 3, 4], dtype=np.float16)
values

array([1., 2., 3., 4.], dtype=float16)

In [42]:
values = np.array([1, 2, 3, 4], dtype='str_')
values

array(['1', '2', '3', '4'], dtype='<U1')

In [46]:
# np.sctypeDict

In [47]:
np.float16(3)

3.0

In [48]:
np.complex64(10)

(10+0j)

In [52]:
np.int32(15.5)

15

In [ ]:
# values = np.array([1, 2, 500], dtype='int8')
# values

In [ ]:
np.complex64(values)

In [ ]:
b = np.complex64(values)

In [ ]:
np.int32(b)

In [53]:
values = np.array((1, 2, 3))
values

array([1, 2, 3])

In [54]:
values = np.array("Hello there")
values

array('Hello there', dtype='<U11')

In [55]:
values = np.array([[1, 2], [3, 4], [5, 6]])
values

array([[1, 2],
       [3, 4],
       [5, 6]])

In [56]:
values.shape

(3, 2)

In [58]:
values = np.array([[1, 2], [3, 4], [5, 6, 7]])
values

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

In [60]:
values = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])
values

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [61]:
values.shape

(3, 2, 2)

In [62]:
values[0]

array([[1, 2],
       [3, 4]])

In [63]:
values[0].shape

(2, 2)

In [64]:
values[0][1][0]

3

In [65]:
values[0, 1, 0]

3

# Создание типовых тензоров

In [66]:
values = np.array([0] * 10)
values

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [69]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [70]:
values = np.array(range(10))
values

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
[el for el in range(1, 21) if el % 2 == 0]

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]

In [71]:
values = np.array([el for el in range(1, 21) if el % 2 == 0])
values

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [75]:
values = np.empty(shape=(3,))
values

array([0., 0., 0.])

In [77]:
values.dtype

dtype('float64')

In [74]:
values = np.empty(shape=(3, 3), dtype=np.int16)
values

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int16)

In [78]:
values = np.empty(shape=(3,3), dtype=np.float16)
values

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float16)

In [79]:
values = np.empty(shape=(3,3), dtype=np.complex64)
values

array([[0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j]], dtype=complex64)

In [80]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [81]:
np.eye(N=4, M=3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [82]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [83]:
np.identity(5, dtype=np.int8)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=int8)

In [84]:
np.zeros((3,))

array([0., 0., 0.])

In [85]:
np.ones((3,))

array([1., 1., 1.])

In [89]:
np.full(4, -3)

array([-3, -3, -3, -3])

In [88]:
np.ones((3,)) * -1

array([-1., -1., -1.])

In [90]:
%%timeit
values = np.array([0] * 10000)

259 µs ± 927 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [91]:
%%timeit
values = np.zeros(10000)

1.18 µs ± 3.43 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [93]:
values = np.mat("1 2 3 4")
values

matrix([[1, 2, 3, 4]])

In [94]:
values.shape

(1, 4)

In [95]:
values = np.mat("1 2; 3 4")
values

matrix([[1, 2],
        [3, 4]])

In [97]:
values.shape

(2, 2)

In [98]:
type(values)

numpy.matrix

In [99]:
isinstance(values, np.ndarray)

True

In [100]:
values = np.matrix("1 2; 3 4")
values

matrix([[1, 2],
        [3, 4]])

In [104]:
values = np.matrix("1 2; 3 4")
print(type(values))
values = np.array(values)
print(type(values))
values

<class 'numpy.matrix'>
<class 'numpy.ndarray'>


array([[1, 2],
       [3, 4]])

In [105]:
values = np.matrix("1 2; 3 4").astype(np.ndarray)
values

matrix([[1, 2],
        [3, 4]], dtype=object)

In [106]:
np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [107]:
np.diag([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

array([1, 5, 9])

In [108]:
np.tri(4)

array([[1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 1., 0.],
       [1., 1., 1., 1.]])

In [109]:
np.tri(4, 2)

array([[1., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [110]:
np.tri(3, 4)

array([[1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 1., 0.]])

In [111]:
np.tri(4)

array([[1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 1., 0.],
       [1., 1., 1., 1.]])

In [112]:
np.tri(4).T

array([[1., 1., 1., 1.],
       [0., 1., 1., 1.],
       [0., 0., 1., 1.],
       [0., 0., 0., 1.]])

In [113]:
values = np.array([[1,2,3], [4,5,6], [7,8,9]])
values

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [114]:
np.tril(values)

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

In [115]:
np.triu(values)

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9]])

In [116]:
np.tril([1, 2, 3, 4])

array([[1, 0, 0, 0],
       [1, 2, 0, 0],
       [1, 2, 3, 0],
       [1, 2, 3, 4]])

In [117]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [118]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [119]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [120]:
np.arange(1, 10, .2)

array([1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4, 2.6, 2.8, 3. , 3.2, 3.4,
       3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. , 5.2, 5.4, 5.6, 5.8, 6. ,
       6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6, 7.8, 8. , 8.2, 8.4, 8.6,
       8.8, 9. , 9.2, 9.4, 9.6, 9.8])

In [121]:
np.arange(0, np.pi, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1])

In [122]:
np.cos(np.arange(0, np.pi, 0.1))

array([ 1.        ,  0.99500417,  0.98006658,  0.95533649,  0.92106099,
        0.87758256,  0.82533561,  0.76484219,  0.69670671,  0.62160997,
        0.54030231,  0.45359612,  0.36235775,  0.26749883,  0.16996714,
        0.0707372 , -0.02919952, -0.12884449, -0.22720209, -0.32328957,
       -0.41614684, -0.5048461 , -0.58850112, -0.66627602, -0.73739372,
       -0.80114362, -0.85688875, -0.90407214, -0.94222234, -0.97095817,
       -0.9899925 , -0.99913515])

In [123]:
%%timeit

np.cos(np.arange(0, np.pi, 0.1))

638 ns ± 6.05 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [124]:
%%timeit
 
result = []
for el in np.arange(0, np.pi, 0.1):
    result.append(np.cos(el))

13 µs ± 61.5 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [125]:
np.linspace(0, np.pi, 0)

array([], dtype=float64)

In [126]:
np.linspace(0, np.pi, 1)

array([0.])

In [127]:
np.linspace(0, np.pi, 2)

array([0.        , 3.14159265])

In [128]:
np.linspace(0, np.pi, 3)

array([0.        , 1.57079633, 3.14159265])

In [129]:
np.linspace(0, np.pi, 10)

array([0.        , 0.34906585, 0.6981317 , 1.04719755, 1.3962634 ,
       1.74532925, 2.0943951 , 2.44346095, 2.7925268 , 3.14159265])

In [130]:
np.logspace(0, np.pi, 10)

array([1.00000000e+00, 2.23391092e+00, 4.99035798e+00, 1.11480152e+01,
       2.49036728e+01, 5.56325865e+01, 1.24278242e+02, 2.77626522e+02,
       6.20192919e+02, 1.38545573e+03])

In [131]:
np.geomspace(1, 4, 3)

array([1., 2., 4.])

In [132]:
values = np.geomspace(1, 4, 10)
values

array([1.        , 1.16652904, 1.36079   , 1.58740105, 1.85174942,
       2.16011948, 2.5198421 , 2.93946898, 3.42897593, 4.        ])

In [133]:
values[1] * values[1]

1.360790000174377

In [134]:
values[1] * values[1] * values[1]

1.5874010519681994

In [135]:
values = np.geomspace(1, 4, 10)
values

array([1.        , 1.16652904, 1.36079   , 1.58740105, 1.85174942,
       2.16011948, 2.5198421 , 2.93946898, 3.42897593, 4.        ])

In [136]:
b = values

In [138]:
b[0] = -10
print(b)
print(values)

[-10.           1.16652904   1.36079      1.58740105   1.85174942
   2.16011948   2.5198421    2.93946898   3.42897593   4.        ]
[-10.           1.16652904   1.36079      1.58740105   1.85174942
   2.16011948   2.5198421    2.93946898   3.42897593   4.        ]


In [139]:
values = np.geomspace(1, 4, 10)

b = np.copy(values)

In [140]:
b[0] = -10
print(b)
print(values)

[-10.           1.16652904   1.36079      1.58740105   1.85174942
   2.16011948   2.5198421    2.93946898   3.42897593   4.        ]
[1.         1.16652904 1.36079    1.58740105 1.85174942 2.16011948
 2.5198421  2.93946898 3.42897593 4.        ]


In [141]:
def get_range(x_index, y_index):
    return 100 * x_index + y_index

np.fromfunction(get_range, (3, 3))

array([[  0.,   1.,   2.],
       [100., 101., 102.],
       [200., 201., 202.]])

In [142]:
np.fromfunction(lambda x_index, y_index: 100 * x_index + y_index, (3, 3))

array([[  0.,   1.,   2.],
       [100., 101., 102.],
       [200., 201., 202.]])

In [143]:
np.fromiter([1,2,3], dtype='int')

array([1, 2, 3])

In [144]:
np.fromiter((1,2,3), dtype='int')

array([1, 2, 3])

In [145]:
np.fromiter("Hello there", dtype='U1')

array(['H', 'e', 'l', 'l', 'o', ' ', 't', 'h', 'e', 'r', 'e'], dtype='<U1')

In [146]:
np.fromiter(range(10), dtype=np.int16)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int16)

In [147]:
def get_range_iterator(N):
    for i in range(N):
        yield i
        
np.fromiter(get_range_iterator(10), dtype=np.int16)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int16)

In [148]:
np.fromstring("1 2 3", dtype="int8", sep=" ")

array([1, 2, 3], dtype=int8)

In [149]:
np.fromstring("1;2;3", dtype="int8", sep=";")

array([1, 2, 3], dtype=int8)

In [150]:
np.fromstring("1 2 3", dtype="U1", sep=" ")

ValueError: don't know how to read character strings with that array type

In [159]:
def get_func(N):
    for i in range(N):
        print("Before")
        return i
        print("After")

In [183]:
get_func(10)

Before


0

In [ ]:
class FOO:
    def __init__(self):
        pass
    def __iter__(self):
        pass

In [219]:
def get_gen(N):
    i = 0
    while i < 30:
        print(f"{i} Before")
        yield i
        print(f"{i} after")
        i += 3

In [220]:
generator = get_gen(10)

In [226]:
value = next(generator)
print(f"value: {value}")

12 after
15 Before
value: 15


In [206]:
for i in get_gen(10):
    print(i)

0 Before
0
0 after
1 Before
1
1 after
2 Before
2
2 after
3 Before
3
3 after
4 Before
4
4 after
5 Before
5
5 after
6 Before
6
6 after
7 Before
7
7 after
8 Before
8
8 after
9 Before
9
9 after


# Свойства и представление тензоров

In [151]:
values = np.array([0.1, 0.2, 0.3], dtype='float64')
values

array([0.1, 0.2, 0.3])

In [ ]:
values.dtype

In [ ]:
values.dtype = np.int8()

In [ ]:
values

In [ ]:
values.size

In [ ]:
values.dtype = np.float64()
values

In [ ]:
print(f"{values.itemsize} byte for each element")

In [ ]:
values.size * values.itemsize

In [ ]:
values = np.ones((3, 2, 4))
values

In [ ]:
values.ndim

In [ ]:
values.shape

In [ ]:
values.shape = 24
values

In [ ]:
values.shape = (3, 8)
values

In [ ]:
values.shape = (3, 2, 4)
b = values.reshape((3,8))

In [ ]:
values

In [ ]:
b

In [ ]:
id(values), id(b)

In [ ]:
values[0,0,0] = 10

In [ ]:
values

In [ ]:
b

In [ ]:
values = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
values

In [ ]:
b = values.T

b

In [ ]:
b[0,0] = -10

In [ ]:
b

In [ ]:
values

In [ ]:
values = np.array([[1,2], [3,4]])
b = values.flatten()

print(values)
print()
print(b)

In [ ]:
values[0,0] = -5

In [ ]:
print(values)
print()
print(b)

In [ ]:
values = np.array([[1,2], [3,4]])
values

In [ ]:
b = values.view()

In [ ]:
b

In [ ]:
values[0,0] = -5

print(values)
print()
print(b)

In [ ]:
values = np.array([[1,2], [3,4]])
b = values

values.shape = (4,)

In [ ]:
print(values)
print(b)

In [ ]:
values = np.array([[1,2], [3,4]])
b = values.view()

values.shape = (4,)

In [ ]:
values

In [ ]:
b

In [ ]:
values = np.array([1,2,3,4])
b = np.array(values)

values[0] = -10

print(values)
print(b)

In [ ]:
values = np.array([1,2,3,4])
b = np.copy(values)

values[0] = -10

print(values)
print(b)

In [ ]:
values = np.array([1,2,3,4])
b = values.copy()

values[0] = -10

print(values)
print(b)

# Изменение формы массивов

In [2]:
import numpy as np
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
b = a.reshape(2,5)
b

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [4]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
a[0] = -3

print(a)
print()
print(b)

[-3  1  2  3  4  5  6  7  8  9]

[[-3  1  2  3  4]
 [ 5  6  7  8  9]]


In [6]:
c = a.reshape(9)

ValueError: cannot reshape array of size 10 into shape (9,)

In [7]:
a.shape = (3,3)

ValueError: cannot reshape array of size 10 into shape (3,3)

In [8]:
a.shape = (-1, 2)
a

array([[-3,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9]])

In [9]:
b.reshape(2, -1)

array([[-3,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9]])

In [10]:
a.ravel()

array([-3,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [ ]:
a.shape = -1

a

In [ ]:
a.resize(2, 5)

a

In [ ]:
a = np.arange(10)
a.resize(3, 3, refcheck=False)

In [ ]:
a

In [ ]:
a.resize(4,5, refcheck=False)

In [ ]:
a

In [ ]:
a = np.arange(9).reshape((3,3))
a

In [ ]:
a.T

In [ ]:
np.arange(10).T

In [ ]:
a = np.arange(10).reshape((1,-1))
a

In [ ]:
a.T

In [ ]:
x = np.arange(32).reshape((8,2,2))
x.shape

In [ ]:
x4 = np.expand_dims(x, axis=0)
x4.shape

In [ ]:
x4 = np.expand_dims(x, axis=1)
x4.shape

In [ ]:
x4 = np.expand_dims(x, axis=-1)
x4.shape

In [ ]:
x4 = x[None, :, :, :]
x4.shape

In [ ]:
x4 = x[:, :, None, :]
x4.shape

In [ ]:
x4 = x[None, :]
x4.shape

In [ ]:
x4 = x[np.newaxis, :]
x4.shape

In [ ]:
x4 = x[:, np.newaxis, :]
x4.shape

In [ ]:
x4 = x[np.newaxis, :, np.newaxis, :]
x4.shape

In [ ]:
x4 = np.expand_dims(x, axis=0)
x44 = np.append(x4, x4, axis=0)
x44.shape

In [ ]:
b = np.delete(x44, 0, axis=0)
b.shape

In [ ]:
b.squeeze().shape

In [ ]:
b.squeeze(axis=0).shape

In [ ]:
b.squeeze(axis=1).shape

# Объединение и разделение массивов

In [11]:
import numpy as np

In [12]:
a = np.array([[1,2], [3,4]])
b = np.array([[-1,-2], [-3,-4]])

In [13]:
np.vstack([a,b])

array([[ 1,  2],
       [ 3,  4],
       [-1, -2],
       [-3, -4]])

In [14]:
np.hstack([a,b])

array([[ 1,  2, -1, -2],
       [ 3,  4, -3, -4]])

In [19]:
a = np.fromiter(range(10), dtype='float').reshape(1,2,5)
b = np.fromiter(range(10, 20), dtype='float').reshape(1,2,5)

a, b

(array([[[0., 1., 2., 3., 4.],
         [5., 6., 7., 8., 9.]]]),
 array([[[10., 11., 12., 13., 14.],
         [15., 16., 17., 18., 19.]]]))

In [26]:
np.vstack([a,b])

array([[[ 0.,  1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.,  9.]],

       [[10., 11., 12., 13., 14.],
        [15., 16., 17., 18., 19.]]])

In [23]:
np.hstack([a,b])

array([[[ 0.,  1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.,  9.],
        [10., 11., 12., 13., 14.],
        [15., 16., 17., 18., 19.]]])

In [ ]:
a = np.fromstring('1 2 3 4', sep=' ')
b = np.fromstring('-1 -2 -3 -4', sep=' ')


In [24]:
np.column_stack([a,b])

array([[[ 0.,  1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.,  9.],
        [10., 11., 12., 13., 14.],
        [15., 16., 17., 18., 19.]]])

In [25]:
np.row_stack([a,b])

array([[[ 0.,  1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.,  9.]],

       [[10., 11., 12., 13., 14.],
        [15., 16., 17., 18., 19.]]])

In [ ]:
a = np.fromiter(range(10), dtype='float').reshape(1,2,5)
b = np.fromiter(range(10, 20), dtype='float').reshape(1,2,5)

a.shape, b.shape

In [ ]:
np.concatenate([a,b], axis=0).shape

In [ ]:
np.concatenate([a,b], axis=1).shape

In [ ]:
np.concatenate([a,b], axis=2).shape

In [ ]:
np.r_[[1,2,3], 4]

In [ ]:
np.r_[[[1,2,3], [1,2,3]], [[4,5,6]]]

In [ ]:
np.c_[[[1,2,3]], [[4]]]

In [ ]:
np.c_[[[1,2,3]], [[4]]].shape

In [ ]:
np.split(np.arange(10), 2)

In [ ]:
np.split(np.arange(11), 2)

In [ ]:
a = np.fromiter(range(18), dtype='float').reshape(3,3,2)

In [ ]:
values = np.array_split(a, 2, axis=-1)

values[0].shape, values[1].shape

# индексация, срезы, итерирование массивов

In [ ]:
a = np.arange(12)

In [ ]:
a

In [ ]:
a[2]

In [ ]:
a[0]

In [ ]:
a[-1]

In [ ]:
a[-2]

In [ ]:
a[100]

In [ ]:
a[0] = 100

a

In [ ]:
a[1:3]

In [ ]:
b = a[1:3]
b

In [ ]:
b[0]= -100

In [ ]:
b

In [ ]:
a

In [ ]:
a[3:]

In [ ]:
a[4:-1]

In [ ]:
a[1:6:2]

In [ ]:
a[::2]

In [ ]:
a[::-1]

In [ ]:
a[:4] = [-1,-2,-3,-4]
a

In [ ]:
for el in a:
    print(el ,end=' ', sep=' ')

In [ ]:
[el/2 for el in a]

In [ ]:
x = np.array([[1,2,3], [10, 20, 30], [100,200,300]])
x

In [ ]:
x[1,1]

In [ ]:
x[-1,-1]

In [ ]:
x[0]

In [ ]:
x[:, 1]

In [ ]:
for row in x:
    for val in row:
        print(val, end=" ")
    print()

In [ ]:
for el in x.flat:
    print(el, end=" ")

In [ ]:
a = np.arange(1, 82).reshape(3,3,3,3)
a.shape

In [ ]:
a[1,2,0,1]

In [ ]:
a = np.arange(10, 20)
a

In [ ]:
a[[0, 3, 4]]

In [ ]:
b = a[[0, 3, 4]]
b

In [ ]:
b[0] = -100

b

In [ ]:
a

In [ ]:
a[[0, 3, 9]] = -1

a

In [ ]:
indx = [0, 1, 9]

a[indx]

In [ ]:
print(a)
a[[True, False, False, True, False, False, False, False, False, False]]

In [ ]:
print(a > 5)
a[a > 5]

# Базовые математические операции

In [ ]:
lst = [1,2,3]
a = np.array([1,2,3])

In [ ]:
lst * 2

In [ ]:
a * 2

In [ ]:
-a 

In [ ]:
a - 3

In [ ]:
a + 2

In [ ]:
2 + a

In [ ]:
a * 5

In [ ]:
a / 5

In [ ]:
a // 2

In [ ]:
a ** 2

In [ ]:
a % 2

In [ ]:
b = np.array([3,4,5])

In [ ]:
a - b

In [ ]:
a + b, b + a

In [ ]:
a * b, b * a

In [ ]:
a / b

In [ ]:
b ** a

In [ ]:
b = np.array([3,4,5,6])

In [ ]:
a + b

In [ ]:
b = np.arange(1, 7).reshape(2,3)
b

In [ ]:
a + b

In [ ]:
a = np.arange(1, 19).reshape(3, 3, 2)
b = np.ones((3,2))

In [ ]:
a - b

In [ ]:
(a - b).shape

In [ ]:
a = np.array([1,2,3,4])
a

In [ ]:
a += 4
a

In [ ]:
a = np.array([1,2,3,4])
b = np.array([0.2, 0.3,0.4, 0.5])

a, b

In [ ]:
a + b

In [ ]:
a += b

# Булевы операции и функции, inf, nan

In [ ]:
a = np.array([1,2,3,10,20,30])
a

In [ ]:
a[a > 5]

In [ ]:
a > 5

In [ ]:
b = np.array([1,2,3,4,5,6])
b

In [ ]:
a == b

In [ ]:
a != b

In [ ]:
a != 2 

In [ ]:
np.greater(a, b)

In [ ]:
np.equal(a, b)

In [ ]:
if (a == b): print("Wow")

In [ ]:
a == b

In [ ]:
res = "Wow" if np.array_equal(a,b) else "Yeah"
res

In [ ]:
res = "Wow" if np.all(a == b) else "Yeah"
res

In [ ]:
res = "Wow" if np.any(a == b) else "Yeah"
res

In [ ]:
res = "Wow" if all(a == b) else "Yeah"
res

In [ ]:
res = "Wow" if any(a == b) else "Yeah"
res

In [ ]:
a / 0

In [ ]:
b = np.array([1,2, np.inf])
b

In [ ]:
b * 0

In [ ]:
(b * 0).sum()

In [ ]:
b = np.array([1,2, np.nan, np.inf, -np.inf])
b

In [ ]:
np.isinf(b)

In [ ]:
np.isnan(b)

In [ ]:
b[np.isinf(b)]

In [ ]:
b[~np.isinf(b)]

In [ ]:
np.isfinite(b), b[np.isfinite(b)]

In [ ]:
a = np.array([1 + 2j, 3-4j, 5])
a

In [ ]:
np.iscomplex(a)

In [ ]:
np.isreal(a)

In [ ]:
x = np.array([True, False, True, False, ])
y = np.array([True, True, False, False, ])

x, y

In [ ]:
np.logical_and(x, y)

In [ ]:
x & y

In [ ]:
np.logical_or(x, y)

In [ ]:
x | y

In [ ]:
np.logical_not(x)

In [ ]:
~x

In [ ]:
x = np.array([1, 0, 1, 0, ])
y = np.array([1, 1, 0, 0, ])

x, y

In [ ]:
x & y

# Базовые математические функции

In [ ]:
a = np.array([1, 2, 3, 10, 20, 30])
a

In [ ]:
a.sum(), np.sum(a)

In [ ]:
a.mean(), np.mean(a)

In [ ]:
a.max(), np.max(a)

In [ ]:
a.min(), np.min(a)

In [ ]:
a = np.arange(10).reshape(2,5)
a

In [ ]:
a.sum(), a.mean()

In [ ]:
a.sum(axis=0)

In [ ]:
a = np.array([-1,-2,2,1])

In [ ]:
np.abs(a)

In [ ]:
np.abs(3)

In [ ]:
np.log2(a)

In [ ]:
np.argmax(a)

In [ ]:
np.argmin(a)

In [ ]:
np.round(0.335, 2)

In [ ]:
np.sin
np.cos
np.tan
np.arcsin
np.arccos
np.arctan

np.median
np.var
np.std
np.cov
np.corrcoef
np.correlate

In [ ]:
np.random.random()

In [ ]:
np.random.randint(1, 10)

In [ ]:
np.random.randint(1, 10, size=3)

In [ ]:
np.random.randn(2)

In [ ]:
np.random.randn(2,3)

In [ ]:
np.random.seed(42)
np.random.randn(2,3)

In [ ]:
a = np.random.randn(5)
a

In [ ]:
np.random.shuffle(a)

In [ ]:
a

In [ ]:
np.random.permutation(a)

# Элементы линейной алгебры

# Множества и операции над ними

# Транспонирование массивов